name: CI

on:
  push:
    branches:
      - master
env:
  env_var: ${{ vars.ENV_CONTEXT_VAR }}

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['8.4', '8.5']

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: curl, mbstring, intl, xdebug
          tools: composer

      - name: Install Composer dependencies
        run: composer install --no-progress --no-suggest

      - name: Run PHP tests dte temp
        env:
          LIBREDTE_HASH: ${{ secrets.LIBREDTE_HASH }}
          LIBREDTE_RUT: ${{ vars.LIBREDTE_RUT }}
        run: |
          composer tests-readonly

      - name: Upload PHPUnit result report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: tests-testdox-php_${{ matrix.php-version }}.txt
          path: var/tests-testdox.txt

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: tests-coverage-php_${{ matrix.php-version }}.txt
          path: var/tests-coverage.txt

      - name: Display PHP version
        run: php -v
