name: CI

on:
  push:
    branches:
      - main  # Ejecuta pruebas al hacer push en la rama 'master'
env:
  env_var: ${{ vars.ENV_CONTEXT_VAR }}

jobs:
  display-variables:
    name: ${{ vars.JOB_NAME }}
    # You can use configuration variables with the `vars` context for dynamic jobs
    if: ${{ vars.USE_VARIABLES == 'true' }}
    runs-on: ${{ vars.RUNNER }}
    environment: ${{ vars.ENVIRONMENT_STAGE }}
    steps:
    - name: Use variables
      run: |
        echo "LIBREDTE_HASH : $LIBREDTE_HASH"
        echo "LIBREDTE_RUT : $LIBREDTE_RUT"
      env:
        LIBREDTE_HASH: ${{ secrets.LIBREDTE_HASH }}
        LIBREDTE_RUT: ${{ vars.LIBREDTE_RUT }}

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['7.3', '8.0']  # Puedes cambiar las versiones según necesites

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}  # Configura la versión de PHP desde la matriz
          extensions: curl, mbstring, intl, xdebug
          tools: composer

      - name: Install Composer dependencies
        run: composer install --no-progress --no-suggest

      - name: Run PHP tests dte temp
        env:
          LIBREDTE_HASH: ${{ secrets.LIBREDTE_HASH }}
          LIBREDTE_RUT: ${{ vars.LIBREDTE_RUT }}
        run: |
          composer tests_dte_temp

      - name: Upload PHPUnit result report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: tests-testdox-php_${{ matrix.php-version }}.txt
          path: var/tests-testdox.txt

      - name: Display PHP version
        run: php -v