name: Docs

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Download phpDocumentor
        run: |
          mkdir -p tools
          wget https://phpdoc.org/phpDocumentor.phar -O tools/phpdocumentor

      - name: Generate Documentation
        run: php tools/phpdocumentor run --config=phpdoc.xml

      - name: Create CNAME file
        run: echo "api-client-php.docs.libredte.cl" > build/docs/CNAME

      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/docs
          publish_branch: gh-pages
